name: schedule_app
description: schedule 

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # Local storage
  shared_preferences: ^2.2.2

  # File picker
  file_picker: ^6.1.1

  # parsing
  csv: ^5.1.1
  excel: ^4.0.2

  # Date formatting
  intl: ^0.19.0

  # Path for saving files
  path_provider: ^2.1.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
